# Generated by Django 4.1.3 on 2022-12-01 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('W_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name',)},
        ),
    ]
